// FILE: lib/src/mutation.dart
import 'query.dart';

/// Represents an executable action (POST, PUT, DELETE) generated by the SDK.
class AxiomMutation<T, Args> {
  /// The generated SDK method that returns the configured Query
  final AxiomQuery<T> Function(Args) mutationFn;

  AxiomMutation(this.mutationFn);
}
