import 'query.dart';

/// Represents an executable action (POST, PUT, DELETE) generated by the SDK.
///
/// The key difference from AxiomQuery is that mutations are NEVER cached.
/// Each call to [mutationFn] fires a fresh network request regardless of
/// whether the same endpoint was called before. This is required for:
///   - Login / token refresh
///   - Form submissions
///   - Delete or update actions
///
/// The runtime routes these through [AxiomRuntime.sendMutation] which bypasses
/// AxiomQueryManager entirely, so second/third clicks always work correctly.
class AxiomMutation<T, Args> {
  /// The generated SDK method that returns the configured Query.
  /// Always backed by sendMutation — never cached.
  final AxiomQuery<T> Function(Args) mutationFn;

  AxiomMutation(this.mutationFn);
}
