
Pod::Spec.new do |s|
  s.name         = 'AxiomRuntime'
  s.version      = '0.1.0'
  s.summary      = 'Axiom native runtime'
  s.description  = 'Auto-generated by Axiom pull'
  s.homepage     = 'https://axiom.dev'
  s.license      = 'MIT'
  s.author       = { 'Axiom' => 'dev@axiom.dev' }
  s.source       = { :path => '.' }
  s.platform     = :ios, '12.0'
  s.static_framework = true
  s.vendored_frameworks = 'AxiomRuntime.xcframework'
end
